import 'package:json_annotation/json_annotation.dart';

part 'news_response_model.g.dart'; // Generated by build_runner

@JsonSerializable()
class NewsArticle {
  final String title;
  final String author;
  final String imgUrl;
  final String desc;
  final DateTime newsDate;
  final int id;
  @JsonKey(name: 'creatAt')
  final DateTime createdAt;

  NewsArticle({
    required this.title,
    required this.author,
    required this.imgUrl,
    required this.desc,
    required this.newsDate,
    required this.id,
    required this.createdAt,
  });

  factory NewsArticle.fromJson(Map<String, dynamic> json) =>
      _$NewsArticleFromJson(json);
  Map<String, dynamic> toJson() => _$NewsArticleToJson(this);
}

@JsonSerializable()
class NewsResponseModel {
  final List<NewsArticle> data;
  final List<String> messages;
  final bool succeeded;

  NewsResponseModel({
    required this.data,
    required this.messages,
    required this.succeeded,
  });

  factory NewsResponseModel.fromJson(Map<String, dynamic> json) =>
      _$NewsResponseModelFromJson(json);
  Map<String, dynamic> toJson() => _$NewsResponseModelToJson(this);
}
